export const ADD_POKEMONS = 'ADD_POKEMONS';
export const SET_ACTIVE_POKEMON = 'SET_ACTIVE_POKEMON';
export const INC_POKEMONS_OFFSET = 'INC_POKEMONS_OFFSET';
export const SET_FIRST_LOADING = 'SET_FIRST_LOADING';
export const SET_CURRENT_LOADING = 'SET_CURRENT_LOADING';
export const SET_POKEMON_SPECIE_DATA = 'SET_POKEMON_SPECIE_DATA';
